fix ENOTCONN error in Node v10.1.0
Node v10.1.0 outputs the following error if process.stdin.end()
is called:

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: shutdown ENOTCONN
    at ReadStream.Socket._final (net.js:369:25)
    at callFinal (_stream_writable.js:615:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

This PR replaces process.stdin.end() with
process.stdin.destroy() to fix the issue.

Fixes: https://github.com/workshopper/stream-adventure/issues/213